//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 06:23:08 PM IST 
//


package com.doms.automation.jaxbclasses.communication;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the communicationorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: communicationorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Order.OrderLines }
     * 
     */
    public Order.OrderLines createOrderOrderLines() {
        return new Order.OrderLines();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine }
     * 
     */
    public Order.OrderLines.OrderLine createOrderOrderLinesOrderLine() {
        return new Order.OrderLines.OrderLine();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineTaxes }
     * 
     */
    public Order.OrderLines.OrderLine.LineTaxes createOrderOrderLinesOrderLineLineTaxes() {
        return new Order.OrderLines.OrderLine.LineTaxes();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineTaxes.LineTax }
     * 
     */
    public Order.OrderLines.OrderLine.LineTaxes.LineTax createOrderOrderLinesOrderLineLineTaxesLineTax() {
        return new Order.OrderLines.OrderLine.LineTaxes.LineTax();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineCharges }
     * 
     */
    public Order.OrderLines.OrderLine.LineCharges createOrderOrderLinesOrderLineLineCharges() {
        return new Order.OrderLines.OrderLine.LineCharges();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineCharges.LineCharge }
     * 
     */
    public Order.OrderLines.OrderLine.LineCharges.LineCharge createOrderOrderLinesOrderLineLineChargesLineCharge() {
        return new Order.OrderLines.OrderLine.LineCharges.LineCharge();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Schedules }
     * 
     */
    public Order.OrderLines.OrderLine.Schedules createOrderOrderLinesOrderLineSchedules() {
        return new Order.OrderLines.OrderLine.Schedules();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.ChildOrderLineRelationships }
     * 
     */
    public Order.OrderLines.OrderLine.ChildOrderLineRelationships createOrderOrderLinesOrderLineChildOrderLineRelationships() {
        return new Order.OrderLines.OrderLine.ChildOrderLineRelationships();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.References }
     * 
     */
    public Order.OrderLines.OrderLine.References createOrderOrderLinesOrderLineReferences() {
        return new Order.OrderLines.OrderLine.References();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.OrderDates }
     * 
     */
    public Order.OrderLines.OrderLine.OrderDates createOrderOrderLinesOrderLineOrderDates() {
        return new Order.OrderLines.OrderLine.OrderDates();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Notes }
     * 
     */
    public Order.OrderLines.OrderLine.Notes createOrderOrderLinesOrderLineNotes() {
        return new Order.OrderLines.OrderLine.Notes();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.PersonInfoShipTo }
     * 
     */
    public Order.OrderLines.OrderLine.PersonInfoShipTo createOrderOrderLinesOrderLinePersonInfoShipTo() {
        return new Order.OrderLines.OrderLine.PersonInfoShipTo();
    }

    /**
     * Create an instance of {@link Order.HeaderTaxes }
     * 
     */
    public Order.HeaderTaxes createOrderHeaderTaxes() {
        return new Order.HeaderTaxes();
    }

    /**
     * Create an instance of {@link Order.HeaderTaxes.TaxSummary }
     * 
     */
    public Order.HeaderTaxes.TaxSummary createOrderHeaderTaxesTaxSummary() {
        return new Order.HeaderTaxes.TaxSummary();
    }

    /**
     * Create an instance of {@link Order.HeaderTaxes.HeaderTax }
     * 
     */
    public Order.HeaderTaxes.HeaderTax createOrderHeaderTaxesHeaderTax() {
        return new Order.HeaderTaxes.HeaderTax();
    }

    /**
     * Create an instance of {@link Order.HeaderCharges }
     * 
     */
    public Order.HeaderCharges createOrderHeaderCharges() {
        return new Order.HeaderCharges();
    }

    /**
     * Create an instance of {@link Order.HeaderCharges.HeaderCharge }
     * 
     */
    public Order.HeaderCharges.HeaderCharge createOrderHeaderChargesHeaderCharge() {
        return new Order.HeaderCharges.HeaderCharge();
    }

    /**
     * Create an instance of {@link Order.Notes }
     * 
     */
    public Order.Notes createOrderNotes() {
        return new Order.Notes();
    }

    /**
     * Create an instance of {@link Order.PaymentMethods }
     * 
     */
    public Order.PaymentMethods createOrderPaymentMethods() {
        return new Order.PaymentMethods();
    }

    /**
     * Create an instance of {@link Order.Extn }
     * 
     */
    public Order.Extn createOrderExtn() {
        return new Order.Extn();
    }

    /**
     * Create an instance of {@link Order.PriceInfo }
     * 
     */
    public Order.PriceInfo createOrderPriceInfo() {
        return new Order.PriceInfo();
    }

    /**
     * Create an instance of {@link Order.Instructions }
     * 
     */
    public Order.Instructions createOrderInstructions() {
        return new Order.Instructions();
    }

    /**
     * Create an instance of {@link Order.PersonInfoBillTo }
     * 
     */
    public Order.PersonInfoBillTo createOrderPersonInfoBillTo() {
        return new Order.PersonInfoBillTo();
    }

    /**
     * Create an instance of {@link Order.Organization }
     * 
     */
    public Order.Organization createOrderOrganization() {
        return new Order.Organization();
    }

    /**
     * Create an instance of {@link Order.OverallTotals }
     * 
     */
    public Order.OverallTotals createOrderOverallTotals() {
        return new Order.OverallTotals();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LinePriceInfo }
     * 
     */
    public Order.OrderLines.OrderLine.LinePriceInfo createOrderOrderLinesOrderLineLinePriceInfo() {
        return new Order.OrderLines.OrderLine.LinePriceInfo();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Item }
     * 
     */
    public Order.OrderLines.OrderLine.Item createOrderOrderLinesOrderLineItem() {
        return new Order.OrderLines.OrderLine.Item();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Extn }
     * 
     */
    public Order.OrderLines.OrderLine.Extn createOrderOrderLinesOrderLineExtn() {
        return new Order.OrderLines.OrderLine.Extn();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineOverallTotals }
     * 
     */
    public Order.OrderLines.OrderLine.LineOverallTotals createOrderOrderLinesOrderLineLineOverallTotals() {
        return new Order.OrderLines.OrderLine.LineOverallTotals();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineTaxes.LineTax.Extn }
     * 
     */
    public Order.OrderLines.OrderLine.LineTaxes.LineTax.Extn createOrderOrderLinesOrderLineLineTaxesLineTaxExtn() {
        return new Order.OrderLines.OrderLine.LineTaxes.LineTax.Extn();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.LineCharges.LineCharge.Extn }
     * 
     */
    public Order.OrderLines.OrderLine.LineCharges.LineCharge.Extn createOrderOrderLinesOrderLineLineChargesLineChargeExtn() {
        return new Order.OrderLines.OrderLine.LineCharges.LineCharge.Extn();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Schedules.Schedule }
     * 
     */
    public Order.OrderLines.OrderLine.Schedules.Schedule createOrderOrderLinesOrderLineSchedulesSchedule() {
        return new Order.OrderLines.OrderLine.Schedules.Schedule();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.ChildOrderLineRelationships.OrderLineRelationship }
     * 
     */
    public Order.OrderLines.OrderLine.ChildOrderLineRelationships.OrderLineRelationship createOrderOrderLinesOrderLineChildOrderLineRelationshipsOrderLineRelationship() {
        return new Order.OrderLines.OrderLine.ChildOrderLineRelationships.OrderLineRelationship();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.References.Reference }
     * 
     */
    public Order.OrderLines.OrderLine.References.Reference createOrderOrderLinesOrderLineReferencesReference() {
        return new Order.OrderLines.OrderLine.References.Reference();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.OrderDates.OrderDate }
     * 
     */
    public Order.OrderLines.OrderLine.OrderDates.OrderDate createOrderOrderLinesOrderLineOrderDatesOrderDate() {
        return new Order.OrderLines.OrderLine.OrderDates.OrderDate();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.Notes.Note }
     * 
     */
    public Order.OrderLines.OrderLine.Notes.Note createOrderOrderLinesOrderLineNotesNote() {
        return new Order.OrderLines.OrderLine.Notes.Note();
    }

    /**
     * Create an instance of {@link Order.OrderLines.OrderLine.PersonInfoShipTo.Extn }
     * 
     */
    public Order.OrderLines.OrderLine.PersonInfoShipTo.Extn createOrderOrderLinesOrderLinePersonInfoShipToExtn() {
        return new Order.OrderLines.OrderLine.PersonInfoShipTo.Extn();
    }

    /**
     * Create an instance of {@link Order.HeaderTaxes.TaxSummary.TaxSummaryDetail }
     * 
     */
    public Order.HeaderTaxes.TaxSummary.TaxSummaryDetail createOrderHeaderTaxesTaxSummaryTaxSummaryDetail() {
        return new Order.HeaderTaxes.TaxSummary.TaxSummaryDetail();
    }

    /**
     * Create an instance of {@link Order.HeaderTaxes.HeaderTax.Extn }
     * 
     */
    public Order.HeaderTaxes.HeaderTax.Extn createOrderHeaderTaxesHeaderTaxExtn() {
        return new Order.HeaderTaxes.HeaderTax.Extn();
    }

    /**
     * Create an instance of {@link Order.HeaderCharges.HeaderCharge.Extn }
     * 
     */
    public Order.HeaderCharges.HeaderCharge.Extn createOrderHeaderChargesHeaderChargeExtn() {
        return new Order.HeaderCharges.HeaderCharge.Extn();
    }

    /**
     * Create an instance of {@link Order.Notes.Note }
     * 
     */
    public Order.Notes.Note createOrderNotesNote() {
        return new Order.Notes.Note();
    }

    /**
     * Create an instance of {@link Order.PaymentMethods.PaymentMethod }
     * 
     */
    public Order.PaymentMethods.PaymentMethod createOrderPaymentMethodsPaymentMethod() {
        return new Order.PaymentMethods.PaymentMethod();
    }

}
